const KEY={users:'zenith_users',user:'zenith_current_user',cart:'zenith_cart',orders:'zenith_orders'};
const get=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const put=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const money=value=>new Intl.NumberFormat('uz-UZ').format(value)+" so'm";
let cart=get(KEY.cart,[]);
const page=()=>document.body.dataset.page||'';
const isAuthPage=()=>page()==='login'||page()==='register';

function cartTotal(){return cart.reduce((sum,item)=>sum+item.qty,0)}
function ensureFloatingCart(){if(isAuthPage()||document.querySelector('.floating-cart'))return;const link=document.createElement('a');link.className='floating-cart';link.href='cart.html';link.setAttribute('aria-label','Savatni ochish');link.innerHTML='🛒<b>0</b>';document.body.append(link)}
function refreshCartBadges(){const count=cartTotal();document.querySelectorAll('#cartCount,.floating-cart b').forEach(node=>node.textContent=count)}
function animateCart(){const button=document.querySelector('.floating-cart');if(!button)return;button.classList.remove('bump');void button.offsetWidth;button.classList.add('bump')}
function add(id){const productId=Number(id);const item=cart.find(entry=>entry.id===productId);item?item.qty+=1:cart.push({id:productId,qty:1});put(KEY.cart,cart);refreshCartBadges();renderCart();animateCart()}
function change(id,delta){const item=cart.find(entry=>entry.id===Number(id));if(!item)return;item.qty+=delta;cart=cart.filter(entry=>entry.qty>0);put(KEY.cart,cart);refreshCartBadges();renderCart()}
function productCard(product){return `<article class="card"><img src="${product.image}" alt="${product.name}" loading="lazy"><div class="card-body"><small>${product.category}</small><h3>${product.name}</h3><p>${product.description}</p><strong class="price">${money(product.price)}</strong><div class="card-actions"><button type="button" onclick="add(${product.id})">Savatga</button><a href="product.html?id=${product.id}">Batafsil</a></div></div></article>`}
function renderProducts(list=PRODUCTS){const root=document.querySelector('#products');if(root)root.innerHTML=list.map(productCard).join('')||'<p class="muted">Mahsulot topilmadi.</p>'}
function renderCart(){const root=document.querySelector('#cart');if(!root)return;let subtotal=0;if(!cart.length){root.innerHTML='<p class="muted">Savat hozircha bo‘sh.</p>'}else{root.innerHTML=cart.map(item=>{const product=PRODUCTS.find(entry=>entry.id===item.id);if(!product)return '';subtotal+=product.price*item.qty;return `<div class="cart-item"><img src="${product.image}" alt="${product.name}"><div><b>${product.name}</b><p class="price">${money(product.price*item.qty)}</p><div class="qty"><button type="button" onclick="change(${product.id},-1)">−</button><span>${item.qty}</span><button type="button" onclick="change(${product.id},1)">+</button></div></div></div>`}).join('')}const subtotalNode=document.querySelector('#subtotal');const totalNode=document.querySelector('#total');if(subtotalNode)subtotalNode.textContent=money(subtotal);if(totalNode)totalNode.textContent=money(subtotal?subtotal+150000:0)}
function initMenu(){const button=document.querySelector('#menu'),nav=document.querySelector('#nav');if(!button||!nav)return;button.addEventListener('click',()=>{const opened=nav.classList.toggle('open');button.setAttribute('aria-expanded',String(opened))});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>nav.classList.remove('open')))}
function initAuthLink(){const user=get(KEY.user,null);const link=document.querySelector('#authLink');if(link){link.textContent=user?'Profil':'Kirish';link.href=user?'profile.html':'login.html'}}
function initProduct(){const root=document.querySelector('#product');if(!root)return;const id=Number(new URLSearchParams(location.search).get('id'));const product=PRODUCTS.find(entry=>entry.id===id)||PRODUCTS[0];root.innerHTML=`<div class="product-detail"><img src="${product.image}" alt="${product.name}"><div><small>${product.category}</small><h1>${product.name}</h1><p class="muted">${product.description}</p><h2 class="price">${money(product.price)}</h2><button class="btn" type="button" onclick="add(${product.id})">Savatga qo‘shish</button></div></div>`}
function initLogin(){const form=document.querySelector('#login');if(!form)return;form.addEventListener('submit',event=>{event.preventDefault();const emailValue=document.querySelector('#email').value.trim().toLowerCase();const passwordValue=document.querySelector('#password').value;const user=get(KEY.users,[]).find(entry=>entry.email.toLowerCase()===emailValue&&entry.password===passwordValue);const message=document.querySelector('#message');if(!user){message.textContent='Email yoki parol noto‘g‘ri';return}put(KEY.user,user);location.href='profile.html'})}
function initRegister(){const form=document.querySelector('#register');if(!form)return;form.addEventListener('submit',event=>{event.preventDefault();const user={name:document.querySelector('#name').value.trim(),email:document.querySelector('#email').value.trim().toLowerCase(),password:document.querySelector('#password').value};const users=get(KEY.users,[]);const message=document.querySelector('#message');if(users.some(entry=>entry.email===user.email)){message.textContent='Bu email avval ro‘yxatdan o‘tgan';return}users.push(user);put(KEY.users,users);put(KEY.user,user);location.href='profile.html'})}
function initProfile(){const user=get(KEY.user,null);const name=document.querySelector('#profileName');if(!name)return;if(!user){location.href='login.html';return}name.textContent=user.name;const email=document.querySelector('#profileEmail');if(email)email.textContent=user.email;document.querySelector('#logout')?.addEventListener('click',()=>{localStorage.removeItem(KEY.user);location.href='index.html'})}
function initOrders(){const root=document.querySelector('#orders');if(!root)return;const user=get(KEY.user,null);const orders=get(KEY.orders,[]).filter(order=>!user||order.user===user.email);root.innerHTML=orders.length?orders.map(order=>`<article class="orders-card"><h3>Buyurtma #${order.id||''}</h3><p>${order.date||''}</p><b class="price">${order.total||''}</b></article>`).join(''):'<p class="muted">Hozircha buyurtmalar yo‘q.</p>'}
function initCheckout(){const button=document.querySelector('#checkout');if(!button)return;button.addEventListener('click',()=>{const user=get(KEY.user,null);if(!user){location.href='login.html';return}if(!cart.length){alert('Savat bo‘sh');return}const orders=get(KEY.orders,[]);orders.push({id:Date.now(),user:user.email,date:new Date().toLocaleString(),items:cart,total:document.querySelector('#total')?.textContent||money(0)});put(KEY.orders,orders);cart=[];put(KEY.cart,cart);refreshCartBadges();renderCart();location.href='orders.html'})}
function init(){ensureFloatingCart();refreshCartBadges();initMenu();initAuthLink();initProduct();initLogin();initRegister();initProfile();initOrders();initCheckout();const search=document.querySelector('#search');renderProducts();search?.addEventListener('input',event=>{const query=event.target.value.toLowerCase().trim();renderProducts(PRODUCTS.filter(product=>(product.name+' '+product.category).toLowerCase().includes(query)))})}
document.addEventListener('DOMContentLoaded',init);